### ISSUE TITLE
Add moodle event(s) for task actions 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_etl#22]
Not 100% sure what is the best way of implementing this, but we sort of need a way to trigger events to let other plugins know that things happened in tool etl.

**Comment by brendanheywood** [comment]
Do you have some specific use cases in mind to help inform the best way forward, eg event vs callback etc?

**Comment by dmitriim** [comment]
Implementation:
- Create a new event 
- Add the event to log actions to add_to_log actions
