### ISSUE TITLE
Extending?

### ISSUE THREAD

**Issue by darrencocco** [catalyst/moodle-tool_etl#5]
Why was it decided to require extending the plugin by creating new classes in processor/source/target folders instead of using sub-plugins?

Why the get_options methods in processor/source/target _base all statically defined? Does that mean to add additional processors/sources/targets would require manually editing these statically defined arrays?

**Comment by dmitriim** [comment]
@darrencocco hey! That the way how the code was design. You can always push a pull request and fix it.

**Comment by darrencocco** [comment]
Thanks, just wanted to make sure I wasn't doing anything that the project owners wouldn't consider merging before I put any effort into it.

**Comment by dmitriim** [comment]
All changes are welcome if they can improve the plugin! Go ahead!

**Comment by dmitriim** [comment]
Looks like it's landed to MOODLE_35 branch.
