### ISSUE TITLE
Iterator data source?

### ISSUE THREAD

**Issue by darrencocco** [catalyst/moodle-tool_etl#6]
For handling large data sources can we add the option to supply an Iterator as a format (e.g. moodle_recordset implements Iterator)?

**Comment by dmitriim** [comment]
@darrencocco If you require this feature please contact us https://www.catalyst-au.net/content/contact-us and we can help you to implement it.

**Comment by darrencocco** [comment]
It is cool, I already added it. I will share it back once it is polished and has some tests. :)

**Comment by dmitriim** [comment]
Cool! Looking forward to see a pull request.

**Comment by dmitriim** [comment]
Looks like it's landed to MOODLE_35 branch.
